name: 直播IP扫描
on:
  workflow_dispatch:
  repository_dispatch:
    types: [直播IP扫描]
jobs:
  build:
    name: 直播IP扫描
    runs-on: ubuntu-latest
    steps:
    - name: 运行脚本
      env:
        TOKEN: ${{ secrets.TOKEN }}
        SCRIPT_REPO: ${{ secrets.SCRIPT_REPO }}
      run: |
        dcount=1 && curl -H "Authorization:token $TOKEN" -skLo zbip_scan.sh "https://raw.githubusercontent.com/xilaochengv/$SCRIPT_REPO/refs/heads/main/zbip_scan.sh"
        while [ "$?" != 0 -a $dcount -lt 3 ];do let dcount++;curl -H "Authorization:token $TOKEN" -skLo zbip_scan.sh "https://raw.githubusercontent.com/xilaochengv/$SCRIPT_REPO/refs/heads/main/zbip_scan.sh";done
        bash -x zbip_scan.sh
