name: 直播IP更新
on:
  workflow_dispatch:
  repository_dispatch:
    types: [zbip_update]
  schedule:
    - cron: "25,55 * * * *"
jobs:
  build:
    name: 直播IP更新
    runs-on: ubuntu-latest
    steps:
    - name: 运行脚本
      env:
        PROXY: ${{ secrets.PROXY }}
        TOKEN: ${{ secrets.TOKEN }}
        COOKIES: ${{ secrets.COOKIES }}
        SCRIPT_REPO: ${{ secrets.SCRIPT_REPO }}
      run: curl -skLH "Authorization:token $TOKEN" "https://raw.githubusercontent.com/xilaochengv/$SCRIPT_REPO/refs/heads/main/zbip_update.sh" | bash
