name: 直播IP更新
on:
  workflow_dispatch:
  repository_dispatch:
    types: [直播IP更新]
jobs:
  build:
    name: 直播IP更新
    runs-on: ubuntu-latest
    steps:
    - name: 运行脚本
      env:
        PROXY: ${{ secrets.PROXY }}
        TOKEN: ${{ secrets.TOKEN }}
        COOKIES: ${{ secrets.COOKIES }}
        SCRIPT_REPO: ${{ secrets.SCRIPT_REPO }}
      run: |
        dcount=1 && curl -H "Authorization:token $TOKEN" -skLo zbip_update.sh "https://raw.githubusercontent.com/xilaochengv/$SCRIPT_REPO/refs/heads/main/zbip_update.sh"
        while [ "$?" != 0 -a $dcount -lt 3 ];do let dcount++;curl -H "Authorization:token $TOKEN" -skLo zbip_update.sh "https://raw.githubusercontent.com/xilaochengv/$SCRIPT_REPO/refs/heads/main/zbip_update.sh";done
        bash -x zbip_update.sh
