name: 直播IP更新
on:
  workflow_dispatch:
  schedule:
    - cron: "25,55 * * * *"
jobs:
  build:
    name: 直播IP更新
    runs-on: ubuntu-latest
    steps:
    - name: 运行脚本
      env:
        REPO: ${{ secrets.REPO }}
        PROXY: ${{ secrets.PROXY }}
        TOKEN: ${{ secrets.TOKEN }}
        COOKIES: ${{ secrets.COOKIES }}
        SCRIPT_REPO: ${{ secrets.SCRIPT_REPO }}
      run: curl -skLH "Authorization:token $TOKEN" "https://raw.githubusercontent.com/xilaochengv/$SCRIPT_REPO/refs/heads/main/zbip_update.sh" | bash
    - name: 上传到Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            iptv_scan
            iptv_zbip
            iptv_need_to_update_cookie
          tag_name: Latest
          body: 直播IP更新与扫描
